Deck.create(name: "Beer Styles")
Card.create(question: "What does IPA stand for?", answer: "India Pale Ale", deck_id: 1)
Card.create(question: "What style is Guiness?", answer: "Stout", deck_id: 1)
Card.create(question: "What German sour beer is traditionally brewed with salt?", answer: "Gose", deck_id: 1)
Card.create(question: "This style is usually efferscent and has flavors reminiscent of banana.", answer: "Hefeweizen", deck_id: 1)
Card.create(question: "Delirium Tremens is one of these.", answer: "Tripel", deck_id: 1)
Card.create(question: "This style is big, boozy and can age very well; think Sierra Nevada BigFoot", answer: "American Barleywine", deck_id: 1)
